-- DropForeignKey
ALTER TABLE "TeamMatch" DROP CONSTRAINT "TeamMatch_userId_fkey";

-- AlterTable
ALTER TABLE "TeamMatch" ALTER COLUMN "auto_start_location" DROP NOT NULL,
ALTER COLUMN "auto_leave_start" DROP NOT NULL,
ALTER COLUMN "auto_intake_reef_succeed" DROP NOT NULL,
ALTER COLUMN "auto_score_l1_succeed" DROP NOT NULL,
ALTER COLUMN "auto_score_l2_succeed" DROP NOT NULL,
ALTER COLUMN "auto_score_l3_succeed" DROP NOT NULL,
ALTER COLUMN "auto_score_l4_succeed" DROP NOT NULL,
ALTER COLUMN "auto_score_processor_succeed" DROP NOT NULL,
ALTER COLUMN "auto_score_net_succeed" DROP NOT NULL,
ALTER COLUMN "auto_intake_reef_fail" DROP NOT NULL,
ALTER COLUMN "auto_score_l1_fail" DROP NOT NULL,
ALTER COLUMN "auto_score_l2_fail" DROP NOT NULL,
ALTER COLUMN "auto_score_l3_fail" DROP NOT NULL,
ALTER COLUMN "auto_score_l4_fail" DROP NOT NULL,
ALTER COLUMN "auto_score_processor_fail" DROP NOT NULL,
ALTER COLUMN "auto_score_net_fail" DROP NOT NULL,
ALTER COLUMN "tele_score_l1_succeed" DROP NOT NULL,
ALTER COLUMN "tele_score_l2_succeed" DROP NOT NULL,
ALTER COLUMN "tele_score_l3_succeed" DROP NOT NULL,
ALTER COLUMN "tele_score_l4_succeed" DROP NOT NULL,
ALTER COLUMN "tele_score_processor_succeed" DROP NOT NULL,
ALTER COLUMN "tele_score_net_succeed" DROP NOT NULL,
ALTER COLUMN "tele_score_l1_fail" DROP NOT NULL,
ALTER COLUMN "tele_score_l2_fail" DROP NOT NULL,
ALTER COLUMN "tele_score_l3_fail" DROP NOT NULL,
ALTER COLUMN "tele_score_l4_fail" DROP NOT NULL,
ALTER COLUMN "tele_score_processor_fail" DROP NOT NULL,
ALTER COLUMN "tele_score_net_fail" DROP NOT NULL,
ALTER COLUMN "endgame" DROP NOT NULL,
ALTER COLUMN "skill" DROP NOT NULL,
ALTER COLUMN "userId" DROP NOT NULL,
ALTER COLUMN "auto_intake_algae_preplaced_fail" DROP NOT NULL,
ALTER COLUMN "auto_intake_algae_preplaced_succeed" DROP NOT NULL,
ALTER COLUMN "auto_intake_coral_preplaced_fail" DROP NOT NULL,
ALTER COLUMN "auto_intake_coral_preplaced_succeed" DROP NOT NULL,
ALTER COLUMN "auto_intake_station_fail" DROP NOT NULL,
ALTER COLUMN "auto_intake_station_succeed" DROP NOT NULL,
ALTER COLUMN "notes" DROP NOT NULL,
ALTER COLUMN "auto_clean_l2_fail" DROP NOT NULL,
ALTER COLUMN "auto_clean_l2_succeed" DROP NOT NULL,
ALTER COLUMN "auto_clean_l3_fail" DROP NOT NULL,
ALTER COLUMN "auto_clean_l3_succeed" DROP NOT NULL,
ALTER COLUMN "tele_clean_l2_fail" DROP NOT NULL,
ALTER COLUMN "tele_clean_l2_succeed" DROP NOT NULL,
ALTER COLUMN "tele_clean_l3_fail" DROP NOT NULL,
ALTER COLUMN "tele_clean_l3_succeed" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "TeamMatch" ADD CONSTRAINT "TeamMatch_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
