name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - name: 'Create env file'
        run: |
          touch .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
      - run: bun install
      - name: Generate Prisma Client
        run: bunx prisma generate
      - name: Prisma Migrate
        run: bunx prisma migrate deploy && bunx prisma db seed
        env:
          DATABASE_URL: postgres://postgres:1234@postgres:5432/postgres_db?schema=public
      - name: Build
        run: bun run build
        env:
          DATABASE_URL: postgres://postgres:1234@postgres:5432/postgres_db?schema=public
