name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    # container: node:latest
    # services:
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_DB: postgres_db
    #       POSTGRES_PASSWORD: 1234
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      # - name: Setup DB
      #   run: bun run db:load
      #   env:
      #     DATABASE_URL: postgres://postgres:1234@postgres:5432/postgres_db?schema=public
      - name: Build
        run: bun run build
        # env:
          # DATABASE_URL: postgres://postgres:1234@postgres:5432/postgres_db?schema=public
